//CATEGORY
export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const CREATE_CATEGORY_SUCCESS="CREATE_CATEGORIES_SUCCESS"
export const DELETE_CATEGORY_SUCCESS="DELETE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_SUCCESS="UPDATE_CATEGORY_SUCCESS"

//NOTE
export const GET_NOTES_SUCCESS="GET_PRODUCTS_SUCCESS"
export const CREATE_NOTE_SUCCESS="CREATE_PRODUCT_SUCCESS"
export const UPDATE_NOTE_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const DELETE_NOTE_SUCCESS="DELETE_NOTE_SUCCESS"


//USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER = 'REGISTER';